---
settings:
  name: NetApp Disaster Recovery
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione NetApp Disaster Recovery
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: reference
  - title: Domande frequenti
    url: "/get-started/dr-faq.html"
  - section: support
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
