= Supporto proxy intelligente
:allow-uri-read: 




=== Supporto proxy intelligente

L'agente NetApp Console supporta il proxy intelligente.  Il proxy intelligente è un modo leggero, sicuro ed efficiente per connettere il tuo sistema locale a NetApp Disaster Recovery.  Fornisce una connessione sicura tra il tuo sistema e NetApp Disaster Recovery senza richiedere una VPN o un accesso diretto a Internet.  Questa implementazione proxy ottimizzata scarica il traffico API all'interno della rete locale.

Quando viene configurato un proxy, NetApp Disaster Recovery tenta di comunicare direttamente con VMware o ONTAP e utilizza il proxy configurato se la comunicazione diretta fallisce.

L'implementazione del proxy NetApp Disaster Recovery richiede la comunicazione sulla porta 443 tra l'agente della console e tutti i server vCenter e gli array ONTAP che utilizzano un protocollo HTTPS.  L'agente NetApp Disaster Recovery all'interno dell'agente Console comunica direttamente con VMware vSphere, VC o ONTAP quando esegue qualsiasi azione.

Per ulteriori informazioni sul proxy intelligente per NetApp Disaster Recovery, vedere https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-setup.html["Configura la tua infrastruttura per NetApp Disaster Recovery"] .

Per ulteriori informazioni sulla configurazione generale del proxy nella NetApp Console, vedere https://docs.netapp.com/us-en/console-setup-admin/task-configuring-proxy.html["Configurare l'agente della console per utilizzare un server proxy"^] .



=== Interrompi la prova gratuita in qualsiasi momento

Puoi interrompere la prova gratuita in qualsiasi momento oppure attendere la sua scadenza.

Vedere https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Termina la prova gratuita"] .
