= Escludere un datastore dai piani di replicazione
:allow-uri-read: 




[[exclude-a-datastore-from-replication-plans]]
=== Escludere un datastore dai piani di replicazione

Quando crei un piano di replica in Disaster Recovery, ora puoi escludere specifici datastore dalla replica. Se una macchina virtuale è configurata per usare più datastore, puoi scegliere quali replicare.

Per dettagli, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"^].



[[removed-password-validation-from-vcenter-password]]
=== Rimossa la convalida della password dalla password vCenter

Disaster Recovery ha rimosso le restrizioni sulle password di vCenter per consentire password che contengono spazi.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/evs-deploy-guide-add-vcenters.html["Aggiungi cluster locali e Amazon EVS vCenter in NetApp Disaster Recovery"^].



[[new-replication-plan-submenu]]
=== Nuovo sottomenu del piano di replicazione

Il Disaster Recovery ora include nuove opzioni di menu per avviare gli aggiornamenti di vCenter dal dashboard del piano di replica. Puoi accedere al sottomenu dal menu azioni del dashboard del piano di replica: seleziona **Plan Health** e poi **Refresh Source vCenter / Refresh Target vCenter**.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#modify-a-replication-plan["Modificare un piano di replicazione"^].



[[improved-network-discovery]]
=== Scoperta della rete migliorata

Disaster Recovery ora include un miglior rilevamento della rete per supportare una gamma più ampia di configurazioni di rete.
