= Supporto per carichi di lavoro basati su Kubernetes (anteprima)
:allow-uri-read: 




=== Supporto per carichi di lavoro basati su Kubernetes (anteprima)

NetApp Disaster Recovery ora include il supporto per i carichi di lavoro basati su Kubernetes. Con il supporto per Kubernetes, puoi proteggere le applicazioni in esecuzione su cluster Kubernetes, inclusi gli ambienti di virtualizzazione OpenShift. Disaster Recovery supporta link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["qualsiasi versione di Kubernetes attualmente supportata da Trident Protect"^], garantendo un'integrazione perfetta e solide funzionalità di disaster recovery per le applicazioni containerizzate.

Caratteristiche principali del supporto per i carichi di lavoro basati su Kubernetes:

* **Ampia compatibilità**: Disaster Recovery supporta tutte le versioni di Kubernetes compatibili con Trident Protect, inclusa Red Hat OpenShift Virtualization.
* **Protezione incentrata sull'applicazione**: ora è possibile proteggere i carichi di lavoro Kubernetes a livello di applicazione, garantendo il ripristino dei servizi critici durante gli eventi di failover.
* **Orchestrazione semplificata**: Disaster Recovery offre flussi di lavoro intuitivi per automatizzare il backup e la replica dei carichi di lavoro Kubernetes, sfruttando la stessa efficiente tecnologia SnapMirror utilizzata per gli ambienti VMware.


Il supporto per i carichi di lavoro basati su Kubernetes è attualmente in anteprima. Per iniziare a proteggere i carichi di lavoro basati su Kubernetes, consultare link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Requisiti di Kubernetes per NetApp Disaster Recovery"^].
