---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-prereqs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Prima di continuare a configurare Amazon EVS con NetApp Disaster Recovery, è necessario assicurarsi che siano soddisfatti diversi prerequisiti. 
---
= Prerequisiti per Amazon EVS con NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Prima di continuare a configurare Amazon EVS con NetApp Disaster Recovery, è necessario assicurarsi che siano soddisfatti diversi prerequisiti.

Nello specifico, procedi come segue:

* Creare un account utente vCenter con i privilegi VMware specifici richiesti affinché NetApp Disaster Recovery esegua le operazioni necessarie.
+

NOTE: Si sconsiglia di utilizzare l'account amministratore predefinito "\administrator@vsphere.com".  In alternativa, dovresti creare un account utente specifico per NetApp Disaster Recovery su tutti i cluster vCenter che parteciperanno al processo di DR.  Per un elenco dei privilegi specifici richiesti, vederelink:vcenter-privileges.html["Privilegi vCenter necessari per NetApp Disaster Recovery"] .

* Assicurarsi che tutti gli archivi dati vCenter che ospiteranno le VM protette da NetApp Disaster Recovery si trovino su risorse di storage NetApp ONTAP .
+
Il servizio supporta NFS e VMFS su iSCSI (e non FC) quando si utilizza Amazon FSx su NetApp ONTAP.  Sebbene il servizio supporti FC, Amazon FSx for NetApp ONTAP non lo fa.

* Assicurati che Amazon EVS vCenter sia connesso a un cluster di storage Amazon FSx for NetApp ONTAP .
* Assicurarsi che gli strumenti VMware siano installati su tutte le VM protette.
* Assicurati che la tua rete locale sia connessa alla tua rete AWS VPC tramite un metodo di connessione approvato da Amazon.  Ti consigliamo di utilizzare AWS Direct Connect, AWS Private Link o una VPN AWS Site-to-Site.

