---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 'L"agente NetApp Console orchestra la connessione e la gestione tra la NetApp Console e le risorse di storage cloud o on-prem.' 
---
= Installa l'agente NetApp Console per NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Un agente NetApp Console consente di connettere le distribuzioni NetApp Console alla propria infrastruttura per orchestrare in modo sicuro soluzioni su AWS, Azure, Google Cloud o ambienti on-premises. L'agente Console esegue le azioni che la NetApp Console deve eseguire per gestire la propria infrastruttura dati. L'agente Console interroga costantemente il livello software as a service NetApp Disaster Recovery per eventuali azioni da intraprendere.

Per NetApp Disaster Recovery, le azioni eseguite orchestrano i cluster VMware vCenter e le istanze di storage ONTAP utilizzando API native per ciascun servizio, al fine di fornire protezione alle VM di produzione in esecuzione in una posizione on-premises. Sebbene l'agente Console possa essere installato in qualsiasi posizione della rete, si consiglia di installare l'agente Console nel sito di disaster recovery per NetApp Disaster Recovery. L'installazione nel sito di DR garantisce che, in caso di guasto del sito primario, l'interfaccia utente della NetApp Console mantenga la connessione all'agente Console e possa orchestrare il processo di ripristino all'interno di tale sito di DR.



== Installazione

* Per utilizzare il Disaster Recovery, installare l'agente Console in modalità standard. Per ulteriori informazioni sui tipi di installazione dell'agente Console, visitare https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Scopri le modalità di distribuzione della NetApp Console"^].


I passaggi specifici di installazione dell'agente Console dipendono dal tipo di distribuzione. Vedere link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Scopri di più sugli agenti della console"^] per ulteriori informazioni.


TIP: Il metodo più semplice per installare l'agente Console con Amazon AWS è utilizzare AWS Marketplace. Per dettagli sull'installazione dell'agente Console tramite AWS Marketplace, vedere  https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Crea un agente della Console da AWS Marketplace"^].
