---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introduzione di NetApp Disaster Recovery tramite Amazon EVS e Amazon FSx for NetApp ONTAP. 
---
= Introduzione di NetApp Disaster Recovery tramite Amazon Elastic VMware Service e Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
I clienti dipendono sempre più dalle infrastrutture virtualizzate per i carichi di lavoro di elaborazione di produzione, come quelle basate su VMware vSphere.  Poiché queste macchine virtuali (VM) sono diventate sempre più critiche per le loro attività, i clienti devono proteggerle dagli stessi tipi di disastri a cui sono soggette le loro risorse di elaborazione fisiche.  Le soluzioni di disaster recovery (DR) attualmente offerte sono complesse, costose e richiedono molte risorse.  NetApp, il più grande fornitore di storage utilizzato per infrastrutture virtualizzate, ha un interesse personale nel garantire che le VM dei suoi clienti siano protette allo stesso modo in cui proteggiamo i dati ospitati nello storage ONTAP di qualsiasi tipo.  Per raggiungere questo obiettivo, NetApp ha creato il servizio NetApp Disaster Recovery .

Una delle principali sfide di qualsiasi soluzione DR è la gestione dei costi incrementali di acquisto, configurazione e manutenzione di risorse di elaborazione, rete e storage aggiuntive, solo per fornire un'infrastruttura di replica e ripristino DR.  Un'opzione diffusa per proteggere le risorse virtuali critiche in sede è quella di utilizzare risorse virtuali ospitate nel cloud come infrastruttura di replica e ripristino DR.  Amazon è un esempio di una soluzione di questo tipo, in grado di fornire risorse convenienti e compatibili con le infrastrutture VM ospitate da NetApp ONTAP .

Amazon ha presentato Amazon Elastic VMware Service (Amazon EVS) che abilita VMware Cloud Foundation all'interno del tuo cloud privato virtuale (VPC).  Amazon EVS offre la resilienza e le prestazioni di AWS insieme al noto software e agli strumenti VMware, consentendo di integrare Amazon EVS vCenters come estensione della tua infrastruttura virtualizzata locale.

Sebbene Amazon EVS includa risorse di storage, l'utilizzo di storage nativo può ridurne l'efficacia per le organizzazioni con carichi di lavoro ad alto consumo di storage.  In questi casi, l'abbinamento di Amazon EVS con Amazon FSx for NetApp ONTAP (Amazon FSxN) può fornire una soluzione di storage più flessibile.  Inoltre, quando si utilizzano le soluzioni di storage NetApp ONTAP in locale per ospitare l'infrastruttura VMware, l'utilizzo di Amazon EVS con FSx per ONTAP significa ottenere le migliori funzionalità di interoperabilità e protezione dei dati tra le infrastrutture in locale e quelle ospitate nel cloud.

Per informazioni su Amazon FSx for NetApp ONTAP, vedere https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introduzione ad Amazon FSx for NetApp ONTAP"^] .
