---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introduzione di NetApp Disaster Recovery tramite Amazon EVS e Amazon FSx for NetApp ONTAP. 
---
= Scopri NetApp Disaster Recovery con Amazon Elastic VMware Service e Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery ti aiuta a proteggere i carichi di lavoro VMware replicando i dati dagli ambienti on-premises ad Amazon EVS e Amazon FSx for NetApp ONTAP per il disaster recovery.

Una delle principali sfide di qualsiasi soluzione DR è la gestione dei costi incrementali di acquisto, configurazione e manutenzione di risorse di elaborazione, rete e storage aggiuntive, solo per fornire un'infrastruttura di replica e ripristino DR.  Un'opzione diffusa per proteggere le risorse virtuali critiche in sede è quella di utilizzare risorse virtuali ospitate nel cloud come infrastruttura di replica e ripristino DR.  Amazon è un esempio di una soluzione di questo tipo, in grado di fornire risorse convenienti e compatibili con le infrastrutture VM ospitate da NetApp ONTAP .

Amazon ha introdotto Amazon Elastic VMware Service (Amazon EVS), che abilita VMware Cloud Foundation all'interno del tuo cloud privato (VPC). Amazon EVS offre la resilienza e le prestazioni di AWS, insieme al familiare software e agli strumenti VMware, consentendo ai vCenters di Amazon EVS di integrarsi con la tua infrastruttura virtualizzata on-premises.

Sebbene Amazon EVS includa risorse di storage, l'utilizzo dello storage nativo può ridurne l'efficacia per le organizzazioni con carichi di lavoro che richiedono un elevato utilizzo dello storage. In questi casi, combinare Amazon EVS con Amazon FSx for NetApp ONTAP storage (Amazon FSxN) può offrire una soluzione storage più flessibile. Inoltre, quando usi soluzioni di storage NetApp ONTAP on-premises per ospitare la tua infrastruttura VMware, utilizzare Amazon EVS con FSx for ONTAP offre funzionalità di interoperabilità e protezione dei dati tra ambienti on-premises e cloud.

Per informazioni su Amazon FSx for NetApp ONTAP, vedere https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introduzione ad Amazon FSx for NetApp ONTAP"^] .
