---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: 'NetApp Disaster Recovery è un servizio di disaster recovery basato su cloud che automatizza i flussi di lavoro di disaster recovery.  È possibile monitorare tutti i processi di disaster recovery e determinarne l"avanzamento.' 
---
= Monitorare i lavori di NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Monitora i job di NetApp Disaster Recovery per seguirne stato e avanzamento.



[[view-jobs]]
== Visualizza i lavori

*Ruolo richiesto della NetApp Console* Per eseguire questa attività è necessario il ruolo di Super admin, Disaster recovery admin, Disaster recovery application admin o Disaster recovery viewer. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Scopri di più sui ruoli utente e sulle autorizzazioni in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].

.Passi
. Accedi al https://console.netapp.com/["NetApp Console"^] .
. Dal menu di navigazione a sinistra NetApp Console , selezionare *Protezione* > *Disaster recovery*.
. Dal menu, seleziona *Monitoraggio lavori*.
. Esamina i job, inclusi i relativi timestamp e lo stato.
. Per visualizzare i dettagli di un job, seleziona la sua riga. Per scaricare i dettagli del job per una revisione offline, seleziona il menu delle azioni e poi seleziona **Scarica dettagli job**.
+

TIP: Quando rivedi i dettagli di un'attività, Disaster Recovery mostra l'utente che ha avviato l'attività. Se il responsabile è indicato come "system", Disaster Recovery ha avviato l'attività.

. Per aggiornare le informazioni, seleziona *Aggiorna*.




[[cancel-a-job]]
== Annullare un lavoro

È possibile annullare un'attività in corso o in coda se è bloccata o per dare priorità a un'operazione in sospeso.

*Ruolo della console NetApp richiesto* Per eseguire questa attività è necessario il ruolo di Super amministratore, Amministratore del ripristino di emergenza, Amministratore del failover del ripristino di emergenza o Amministratore dell'applicazione di ripristino di emergenza. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Scopri di più sui ruoli utente e sulle autorizzazioni in NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].

.Passi
. Dalla barra di navigazione sinistra NetApp Console , selezionare *Protezione* > *Disaster recovery*.
. Dal menu, seleziona *Monitoraggio lavori*.
. Nella pagina di monitoraggio dei job, annota l'ID del job che vuoi annullare.
+
Il lavoro deve essere nello stato "In corso" o "In coda".

. Seleziona il menu Azioni, quindi **Annulla job**.

