---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: Prima di utilizzare NetApp Disaster Recovery, assicurati che il tuo ambiente soddisfi i requisiti di storage ONTAP , cluster VMware vCenter e NetApp Console . 
---
= Prerequisiti NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prima di utilizzare NetApp Disaster Recovery, assicurati che il tuo ambiente soddisfi i requisiti di storage ONTAP , cluster VMware vCenter e NetApp Console .



== Versioni del software

[cols="35,55a"]
|===
| Componente | Versione minima 


| Amazon FSx for NetApp ONTAP  a| 
Ultima versione disponibile



| Google Cloud VMware Engine che utilizza Google Cloud NetApp Volumes  a| 
Ultima versione disponibile



| Software ONTAP  a| 
ONTAP 9.10.0 o successivo



| VMware Cloud per AWS  a| 
Ultima versione disponibile



| VMware vCenter on-premise  a| 
7.0u3 o successivo

|===


== Prerequisiti e considerazioni di Google Cloud

Con Disaster Recovery su Google Cloud VMware Engine tramite Google Cloud NetApp Volumes, assicurati di configurare le autorizzazioni corrette e di rispettare le considerazioni indicate.

* Contatta il team Google SRE per consentire l'inserimento nell'elenco di:
+
** API di sincronizzazione per trasferire snapshot dall'archiviazione locale a Google Cloud NetApp Volumes.
** il progetto Google con il motore VMware per la creazione, il montaggio e lo smontaggio di datastore.


* Devilink:https://docs.google.com/forms/d/1zuaHu437MNpUf8i5oByK-OTLWXcNIg0es9t036riYRc/viewform?edit_requested=true["Invia una richiesta per consentire la replica ibrida dei tuoi volumi"^] .
* Siate consapevoli dellink:https://docs.cloud.google.com/netapp/volumes/docs/quotas["Quote e limiti Google Cloud NetApp Volumes"^] .
* È possibile aggiungere un solo volume o datastore a un piano di replica.
* Rivedere illink:../release-notes/dr-limitations.html#limitations-with-google-cloud-netapp-volumes["limitazioni"] .


**Considerazioni sul failover**

* Il failover è supportato solo utilizzando lo snapshot più recente.  Se necessario, è possibile creare un nuovo snapshot durante lo snapshot (ovvero, l'opzione snapshot selettiva deve essere disabilitata).
* Non è possibile creare un nuovo snapshot dopo il failover.
* Non è possibile conservare e riconciliare gli snapshot dopo il failover.


**Considerazioni sul failback**

* Il failback è possibile solo con l'opzione snapshot selettiva.  Non è possibile eseguire un failback eseguendo un nuovo snapshot.
* Se si rimuove il peering dei cluster tra l'archiviazione locale e i cluster di archiviazione Google Cloud NetApp Volumes , è necessario cancellare manualmente la voce relativa al peering delle VM di archiviazione e del cluster dal cluster locale. Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-delete.html["Elimina una relazione peer vserver"^].




=== Autorizzazioni di Google Cloud

Al servizio principale in Google Cloud devono essere assegnati i seguenti ruoli o autorizzazioni equivalenti:

* link:https://docs.cloud.google.com/compute/docs/access/iam["Ruolo di amministratore di calcolo"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Autorizzazioni di Google Cloud per NetApp Console"^]
* link:https://docs.cloud.google.com/iam/docs/roles-permissions/netapp["Amministrazione di Google Cloud NetApp Volumes"]
* link:https://docs.cloud.google.com/vmware-engine/docs/iam#vmware-engine-roles["Amministratore del servizio VMware Engine"^]




=== Autorizzazioni NetApp Console

L'utente NetApp Console deve avere i seguenti ruoli:

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-gcnv-roles.html["Amministratore di Google Cloud NetApp Volumes"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles["Amministratore SnapCenter"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Amministratore del failover del ripristino di emergenza"^]




== Prerequisiti di archiviazione ONTAP

Questi prerequisiti si applicano sia a ONTAP che ad Amazon FSX per le istanze NetApp ONTAP .

* I cluster di origine e di destinazione devono avere una relazione peer.
* L'SVM che ospita i volumi di disaster recovery deve essere presente nel cluster di destinazione.
* L'SVM di origine e l'SVM di destinazione devono avere una relazione peer.
* Se si esegue la distribuzione con Amazon FSx for NetApp ONTAP, si applica il seguente prerequisito:
+
** Nella tua VPC deve essere presente un'istanza Amazon FSx for NetApp ONTAP per ospitare i datastore VMware DR. Per iniziare, vederelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["la documentazione Amazon FSx per ONTAP"^] .






== Prerequisiti dei cluster VMware vCenter

Questi prerequisiti si applicano sia ai cluster vCenter on-premise sia al data center software-defined (SDDC) VMware Cloud for AWS.

* Revisionelink:../reference/vcenter-privileges.html["privilegi vCenter"] necessario per NetApp Disaster Recovery.
* Tutti i cluster VMware che si desidera vengano gestiti NetApp Disaster Recovery utilizzano volumi ONTAP per ospitare tutte le VM che si desidera proteggere.
* Tutti i datastore VMware da gestire tramite NetApp Disaster Recovery devono utilizzare uno dei seguenti protocolli:
+
** NFS
** VMFS che utilizza il protocollo iSCSI o FC


* VMware vSphere versione 7.0 Update 3 (7.0v3) o successiva
* Se si utilizza VMware Cloud SDDC, si applicano i seguenti prerequisiti.
+
** Nella VMware Cloud Console, utilizzare i ruoli di servizio Amministratore e Amministratore NSX Cloud.  Utilizzare anche il proprietario dell'organizzazione per il ruolo Organizzazione. Fare riferimento a https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Utilizzo di VMware Cloud Foundations con AWS FSx per la documentazione NetApp ONTAP"^] .
** Collegare VMware Cloud SDDC all'istanza Amazon FSx for NetApp ONTAP . Fare riferimento a https://vmc.techzone.vmware.com/fsx-guide#overview["Informazioni sull'integrazione di VMware Cloud su AWS con Amazon FSx for NetApp ONTAP"^] .






== Prerequisiti NetApp Console



=== Inizia con la NetApp Console

Se non l'hai ancora fatto, https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html["iscriviti alla NetApp Console e crea un'organizzazione"^] .



=== Raccogli le credenziali per ONTAP e VMware

* Le credenziali Amazon FSx for ONTAP e AWS devono essere aggiunte al sistema all'interno del progetto NetApp Console che gestisce NetApp Disaster Recovery.
* NetApp Disaster Recovery richiede le credenziali vCenter.  Quando si aggiunge un sito in NetApp Disaster Recovery, è necessario immettere le credenziali vCenter.
+
Per un elenco dei privilegi vCenter necessari, fare riferimento alink:../reference/vcenter-privileges.html["Privilegi vCenter necessari per NetApp Disaster Recovery"] .  Per istruzioni su come aggiungere un sito, fare riferimento alink:../use/sites-add.html["Aggiungi un sito"] .





=== Creare l'agente NetApp Console

L'agente Console è un componente software che consente alla Console di comunicare con lo storage ONTAP e i cluster VMware vCenter. È necessario affinché Disaster Recovery funzioni correttamente. L'agente risiede nella tua rete privata (un data center locale o un VPC cloud) e comunica con le tue istanze di archiviazione ONTAP e con qualsiasi componente aggiuntivo di server e applicazioni. Per il Disaster Recovery, si tratta dell'accesso ai cluster vCenter gestiti.

È necessario configurare un agente Console nella NetApp Console.  Quando si utilizza l'agente, questo includerà le funzionalità appropriate per il servizio Disaster Recovery.

* NetApp Disaster Recovery funziona solo con la distribuzione dell'agente in modalità standard. Vedere https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introduzione alla NetApp Console in modalità standard"^] .
* Assicurarsi che sia il vCenter di origine che quello di destinazione utilizzino lo stesso agente Console.
* Tipo di agente console necessario:
+
** *Ripristino di emergenza da locale a locale*: installare l'agente locale della console nel sito di ripristino di emergenza. Utilizzando questo metodo, un errore del sito primario non impedisce al servizio di riavviare le risorse virtuali nel sito DR. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html["Installa e configura l'agente Console in locale"^] .
+
Disaster Recovery supporta anche l'utilizzo di più agenti Console con configurazioni on-premise. In questo scenario, gli agenti della console indirizzano le azioni ai cluster di array vCenter e ONTAP , mentre l'origine e la destinazione avrebbero ciascuna il proprio agente della console. Si consiglia di utilizzare più agenti della console per ridurre la latenza e migliorare i tempi di ripristino in caso di errore di un agente o di un sito della console.

** *Da locale ad AWS*: installa l'agente della console per AWS nella tua VPC AWS. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-install-options-aws.html["Opzioni di installazione dell'agente console in AWS"^] .
+

TIP: Per le connessioni da locale a locale, utilizzare l'agente Console locale.  Per gli ambienti on-premise su AWS, utilizzare l'agente AWS Console, che ha accesso al vCenter on-premise di origine e al vCenter on-premise di destinazione.

** L'agente Console installato deve essere in grado di accedere a tutte le istanze del cluster VMware vCenter e agli host ESXi gestiti dai cluster vCenter che Disaster Recovery gestirà.


* Tutti gli array ONTAP da gestire tramite NetApp Disaster Recovery devono essere aggiunti a qualsiasi sistema all'interno del progetto NetApp Console che verrà utilizzato per gestire NetApp Disaster Recovery.
+
Vedere https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Scopri i cluster ONTAP on-premise"^] .

* Per informazioni sulla configurazione di un proxy intelligente per NetApp Disaster Recovery, vederelink:../get-started/dr-setup.html["Configura la tua infrastruttura per NetApp Disaster Recovery"] .




== Prerequisiti del carico di lavoro

Per garantire il successo dei processi di coerenza delle applicazioni, applicare i seguenti prerequisiti:

* Assicurarsi che gli strumenti VMware (o gli strumenti Open VM) siano in esecuzione sulle VM che verranno protette.
* Per le VM Windows che eseguono Microsoft SQL Server, Oracle Database o entrambi, i database devono avere i relativi VSS Writer abilitati.
* I database Oracle in esecuzione su un sistema operativo Linux devono avere l'autenticazione utente del sistema operativo abilitata per il ruolo SYSDBA del database Oracle.

