---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: Prima di utilizzare NetApp Disaster Recovery, assicurati che il tuo ambiente soddisfi i requisiti di storage ONTAP , cluster VMware vCenter e NetApp Console . 
---
= Prerequisiti NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prima di utilizzare NetApp Disaster Recovery, assicurati che il tuo ambiente soddisfi i requisiti di storage ONTAP , cluster VMware vCenter e NetApp Console .



== Versioni del software

[cols="35,55a"]
|===
| Componente | Versione minima 


| Software ONTAP  a| 
ONTAP 9.10.0 o successivo



| VMware vCenter on-premise  a| 
7.0u3 o successivo



| VMware Cloud per AWS  a| 
Ultima versione disponibile



| Amazon FSx for NetApp ONTAP  a| 
Ultima versione disponibile

|===


== Prerequisiti di archiviazione ONTAP

Questi prerequisiti si applicano sia a ONTAP che ad Amazon FSX per le istanze NetApp ONTAP .

* I cluster di origine e di destinazione devono avere una relazione peer.
* L'SVM che ospita i volumi di disaster recovery deve essere presente nel cluster di destinazione.
* L'SVM di origine e l'SVM di destinazione devono avere una relazione peer.
* Se si esegue la distribuzione con Amazon FSx for NetApp ONTAP, si applica il seguente prerequisito:
+
** Nella tua VPC deve essere presente un'istanza Amazon FSx for NetApp ONTAP per ospitare i datastore VMware DR. Per iniziare, vederelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["la documentazione Amazon FSx per ONTAP"^] .






== Prerequisiti dei cluster VMware vCenter

Questi prerequisiti si applicano sia ai cluster vCenter on-premise sia al data center software-defined (SDDC) VMware Cloud for AWS.

* Revisionelink:../reference/vcenter-privileges.html["privilegi vCenter"] necessario per NetApp Disaster Recovery.
* Tutti i cluster VMware che si desidera vengano gestiti NetApp Disaster Recovery utilizzano volumi ONTAP per ospitare tutte le VM che si desidera proteggere.
* Tutti i datastore VMware da gestire tramite NetApp Disaster Recovery devono utilizzare uno dei seguenti protocolli:
+
** NFS
** VMFS che utilizza il protocollo iSCSI o FC


* VMware vSphere versione 7.0 Update 3 (7.0v3) o successiva
* Se si utilizza VMware Cloud SDDC, si applicano i seguenti prerequisiti.
+
** Nella VMware Cloud Console, utilizzare i ruoli di servizio Amministratore e Amministratore NSX Cloud.  Utilizzare anche il proprietario dell'organizzazione per il ruolo Organizzazione. Fare riferimento a https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Utilizzo di VMware Cloud Foundations con AWS FSx per la documentazione NetApp ONTAP"^] .
** Collegare VMware Cloud SDDC all'istanza Amazon FSx for NetApp ONTAP . Fare riferimento a https://vmc.techzone.vmware.com/fsx-guide#overview["Informazioni sull'integrazione di VMware Cloud su AWS con Amazon FSx for NetApp ONTAP"^] .






== Prerequisiti NetApp Console



=== Inizia con la NetApp Console

Se non l'hai ancora fatto, https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["iscriviti alla NetApp Console e crea un'organizzazione"^] .



=== Raccogli le credenziali per ONTAP e VMware

* Le credenziali Amazon FSx for ONTAP e AWS devono essere aggiunte al sistema all'interno del progetto NetApp Console che gestisce NetApp Disaster Recovery.
* NetApp Disaster Recovery richiede le credenziali vCenter.  Quando si aggiunge un sito in NetApp Disaster Recovery, è necessario immettere le credenziali vCenter.
+
Per un elenco dei privilegi vCenter necessari, fare riferimento alink:../reference/vcenter-privileges.html["Privilegi vCenter necessari per NetApp Disaster Recovery"] .  Per istruzioni su come aggiungere un sito, fare riferimento alink:../use/sites-add.html["Aggiungi un sito"] .





=== Creare l'agente NetApp Console

L'agente Console è un componente software che consente alla Console di comunicare con lo storage ONTAP e i cluster VMware vCenter. È necessario affinché Disaster Recovery funzioni correttamente. L'agente risiede nella tua rete privata (un data center locale o un VPC cloud) e comunica con le tue istanze di archiviazione ONTAP e con qualsiasi componente aggiuntivo di server e applicazioni. Per il Disaster Recovery, si tratta dell'accesso ai cluster vCenter gestiti.

È necessario configurare un agente Console nella NetApp Console.  Quando si utilizza l'agente, questo includerà le funzionalità appropriate per il servizio Disaster Recovery.

* NetApp Disaster Recovery funziona solo con la distribuzione dell'agente in modalità standard. Vedere https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Introduzione alla NetApp Console in modalità standard"^] .
* Assicurarsi che sia il vCenter di origine che quello di destinazione utilizzino lo stesso agente Console.
* Tipo di agente console necessario:
+
** *Ripristino di emergenza da locale a locale*: installare l'agente locale della console nel sito di ripristino di emergenza.  Utilizzando questo metodo, un errore del sito primario non impedisce al servizio di riavviare le risorse virtuali nel sito DR. Fare riferimento a https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installa e configura l'agente Console in locale"^] .
** *Da locale ad AWS*: installa l'agente della console per AWS nella tua VPC AWS. Fare riferimento a https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["Opzioni di installazione dell'agente console in AWS"^] .
+

TIP: Per le connessioni da locale a locale, utilizzare l'agente Console locale.  Per gli ambienti on-premise su AWS, utilizzare l'agente AWS Console, che ha accesso al vCenter on-premise di origine e al vCenter on-premise di destinazione.

** L'agente Console installato deve essere in grado di accedere a tutte le istanze del cluster VMware vCenter e agli host ESXi gestiti dai cluster vCenter che Disaster Recovery gestirà.


* Tutti gli array ONTAP da gestire tramite NetApp Disaster Recovery devono essere aggiunti a qualsiasi sistema all'interno del progetto NetApp Console che verrà utilizzato per gestire NetApp Disaster Recovery.
+
Vedere https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Scopri i cluster ONTAP on-premise"^] .

* Per informazioni sulla configurazione di un proxy intelligente per NetApp Disaster Recovery, vederelink:../get-started/dr-setup.html["Configura la tua infrastruttura per NetApp Disaster Recovery"] .




== Prerequisiti del carico di lavoro

Per garantire il successo dei processi di coerenza delle applicazioni, applicare i seguenti prerequisiti:

* Assicurarsi che gli strumenti VMware (o gli strumenti Open VM) siano in esecuzione sulle VM che verranno protette.
* Per le VM Windows che eseguono Microsoft SQL Server, Oracle Database o entrambi, i database devono avere i relativi VSS Writer abilitati.
* I database Oracle in esecuzione su un sistema operativo Linux devono avere l'autenticazione utente del sistema operativo abilitata per il ruolo SYSDBA del database Oracle.

