---
sidebar: sidebar 
permalink: get-started/reference-vmware-prerequisites.html 
keywords: vmware cluster prerequisites, vmware 
summary: 'Prima di utilizzare NetApp Disaster Recovery, assicurarsi che l"ambiente soddisfi i requisiti del cluster vCenter VMware.' 
---
= Prerequisiti dei cluster VMware vCenter per NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prima di utilizzare NetApp Disaster Recovery, assicurarsi che l'ambiente soddisfi i requisiti del cluster vCenter VMware.



== Requisiti generali

Questi prerequisiti si applicano sia ai cluster vCenter on-premise sia al data center software-defined (SDDC) VMware Cloud for AWS.

* Revisionelink:../reference/vcenter-privileges.html["privilegi vCenter"] necessario per NetApp Disaster Recovery.
* Tutti i cluster VMware che si desidera vengano gestiti NetApp Disaster Recovery utilizzano volumi ONTAP per ospitare tutte le VM che si desidera proteggere.
* Tutti i datastore VMware da gestire tramite NetApp Disaster Recovery devono utilizzare uno dei seguenti protocolli:
+
** NFS
** VMFS che utilizza il protocollo iSCSI o FC


* VMware vSphere versione 7.0 Update 3 (7.0v3) o successiva




== Prerequisiti di VMware Cloud SDDC

Se si utilizza VMware Cloud SDDC, si applicano i seguenti prerequisiti aggiuntivi:

* Nella VMware Cloud Console, utilizzare i ruoli di servizio Amministratore e Amministratore NSX Cloud.  Utilizzare anche il proprietario dell'organizzazione per il ruolo Organizzazione. Fare riferimento a https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Utilizzo di VMware Cloud Foundations con AWS FSx per la documentazione NetApp ONTAP"^] .
* Collegare VMware Cloud SDDC all'istanza Amazon FSx for NetApp ONTAP . Fare riferimento a https://vmc.techzone.vmware.com/fsx-guide#overview["Informazioni sull'integrazione di VMware Cloud su AWS con Amazon FSx for NetApp ONTAP"^] .

