---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: NetApp Disaster Recovery è un servizio di disaster recovery basato su cloud che automatizza i flussi di lavoro di disaster recovery.  Con NetApp Disaster Recovery per VMware, puoi replicare i carichi di lavoro VMware on-premise che eseguono lo storage ONTAP su un data center software-defined VMware nei cloud pubblici come sito di disaster recovery utilizzando lo storage cloud NetApp . 
---
= Novità di NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le novità di NetApp Disaster Recovery.



== 06 ottobre 2025



=== Il BlueXP disaster recovery è ora NetApp Disaster Recovery

Il BlueXP disaster recovery è stato rinominato NetApp Disaster Recovery.



=== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vedere illink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione NetApp Console"] .



=== Altri aggiornamenti

* Il supporto per Amazon Elastic VMware Service (EVS) con Amazon FSx for NetApp ONTAP era disponibile in anteprima pubblica. Con questa versione, la funzionalità è ora disponibile al pubblico. Per i dettagli, fare riferimento alink:../reference/evs-deploy-guide-introduction.html["Introduzione di NetApp Disaster Recovery tramite Amazon Elastic VMware Service e Amazon FSx for NetApp ONTAP"] .
* Miglioramenti nella scoperta dello storage, inclusi tempi di scoperta ridotti per le distribuzioni on-premise
* Supporto per la gestione delle identità e degli accessi (IAM), incluso il controllo degli accessi basato sui ruoli (RBAC) e autorizzazioni utente migliorate
* Supporto di anteprima privata per la soluzione Azure VMware e Cloud Volumes ONTAP. Grazie a questo supporto, ora è possibile configurare la protezione del disaster recovery da locale alla soluzione Azure VMware utilizzando l'archiviazione Cloud Volumes ONTAP .




== 04 agosto 2025

Versione 4.2.5P2



=== Aggiornamenti NetApp Disaster Recovery

Questa versione include i seguenti aggiornamenti:

* Migliorato il supporto VMFS per gestire lo stesso LUN presentato da più macchine virtuali di archiviazione.
* Migliorata la pulizia dello teardown del test per gestire il datastore già smontato e/o eliminato.
* Mappatura della subnet migliorata in modo che ora convalidi che il gateway immesso sia contenuto nella rete fornita.
* È stato risolto un problema che poteva causare il fallimento del piano di replica se il nome della VM conteneva ".com".
* È stata rimossa una restrizione che impediva al volume di destinazione di essere uguale al volume di origine durante la creazione del volume come parte della creazione del piano di replica.
* Aggiunto il supporto per un abbonamento con pagamento in base al consumo (PAYGO) a NetApp Intelligent Services in Azure Marketplace e aggiunto un collegamento ad Azure Marketplace nella finestra di dialogo della prova gratuita.
+
Per i dettagli, vedere https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html#licensing["Licenza NetApp Disaster Recovery"] E https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Impostare la licenza per NetApp Disaster Recovery"] .





== 14 luglio 2025

Versione 4.2.5



=== Ruoli utente in NetApp Disaster Recovery

NetApp Disaster Recovery ora utilizza ruoli per gestire l'accesso di ciascun utente a funzionalità e azioni specifiche.

Il servizio utilizza i seguenti ruoli specifici di NetApp Disaster Recovery.

* *Amministratore del ripristino di emergenza*: esegue qualsiasi azione in NetApp Disaster Recovery.
* *Amministratore failover di disaster recovery*: esegue azioni di failover e migrazione in NetApp Disaster Recovery.
* *Amministratore dell'applicazione di disaster recovery*: crea e modifica piani di replica e avvia failover di prova.
* *Visualizzatore di disaster recovery*: visualizza le informazioni in NetApp Disaster Recovery, ma non può eseguire alcuna azione.


Se si fa clic sul servizio NetApp Disaster Recovery e lo si configura per la prima volta, è necessario disporre dell'autorizzazione *SnapCenterAdmin* o del ruolo *Organization Admin*.

Per maggiori dettagli, vedere  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Ruoli utente e autorizzazioni in NetApp Disaster Recovery"] .

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri i ruoli di accesso per tutti i servizi"^] .



=== Altri aggiornamenti in NetApp Disaster Recovery

* Rilevamento di rete migliorato
* Miglioramenti della scalabilità:
+
** Filtraggio per i metadati richiesti anziché per tutti i dettagli
** Miglioramenti della scoperta per recuperare e aggiornare più velocemente le risorse della VM
** Ottimizzazione della memoria e delle prestazioni per il recupero e l'aggiornamento dei dati
** Miglioramenti nella creazione del client vCenter SDK e nella gestione del pool


* Gestione dei dati obsoleti alla prossima individuazione programmata o manuale:
+
** Quando una VM viene eliminata in vCenter, NetApp Disaster Recovery ora la rimuove automaticamente dal piano di replica.
** Quando un datastore o una rete vengono eliminati in vCenter, NetApp Disaster Recovery li elimina ora dal piano di replica e dal gruppo di risorse.
** Quando un cluster, un host o un data center viene eliminato in vCenter, NetApp Disaster Recovery ora lo elimina dal piano di replica e dal gruppo di risorse.


* Ora puoi accedere alla documentazione di Swagger nella modalità di navigazione in incognito del tuo browser. È possibile accedervi da NetApp Disaster Recovery tramite l'opzione Impostazioni > Documentazione API oppure direttamente al seguente URL nella modalità di navigazione in incognito del browser: https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentazione Swagger"^] .
* In alcune situazioni, dopo un'operazione di failback, l'iGroup veniva lasciato indietro al termine dell'operazione. Questo aggiornamento rimuove iGroup se è obsoleto.
* Se nel piano di replica è stato utilizzato l'FQDN NFS, NetApp Disaster Recovery ora lo risolve in un indirizzo IP. Questo aggiornamento è utile se il nome di dominio completo non è risolvibile nel sito di ripristino di emergenza.
* Miglioramenti dell'allineamento dell'interfaccia utente
* Miglioramenti del registro per acquisire i dettagli delle dimensioni di vCenter dopo la corretta individuazione




== 30 giugno 2025

Versione 4.2.4P2



=== Miglioramenti della scoperta

Questo aggiornamento migliora il processo di individuazione, riducendone il tempo necessario.



== 23 giugno 2025

Versione 4.2.4P1



=== Miglioramenti nella mappatura delle subnet

Questo aggiornamento migliora la finestra di dialogo Aggiungi e modifica mappatura subnet con una nuova funzionalità di ricerca.  Ora puoi trovare rapidamente subnet specifiche inserendo termini di ricerca, semplificando la gestione delle mappature delle subnet.



== 09 giugno 2025

Versione 4.2.4



=== Supporto per la soluzione password dell'amministratore locale di Windows (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) è una funzionalità di Windows che gestisce ed esegue automaticamente il backup della password di un account amministratore locale su Active Directory.

Ora è possibile selezionare le opzioni di mappatura della subnet e selezionare l'opzione LAPS fornendo i dettagli del controller di dominio.  Utilizzando questa opzione non è necessario fornire una password per ciascuna delle macchine virtuali.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



== 13 maggio 2025

Versione 4.2.3



=== Mappatura della sottorete

Con questa versione, è possibile gestire gli indirizzi IP in caso di failover in un modo nuovo, utilizzando la mappatura delle subnet, che consente di aggiungere subnet per ogni vCenter.  In questo modo si definiscono il CIDR IPv4, il gateway predefinito e il DNS per ogni rete virtuale.

In caso di failover, NetApp Disaster Recovery determina l'indirizzo IP appropriato di ogni vNIC esaminando il CIDR fornito per la rete virtuale mappata e lo utilizza per ricavare il nuovo indirizzo IP.

Per esempio:

* ReteA = 10.1.1.0/24
* ReteB = 192.168.1.0/24


VM1 ha una vNIC (10.1.1.50) connessa alla ReteA.  Nelle impostazioni del piano di replica, la rete A è mappata sulla rete B.

In caso di failover, NetApp Disaster Recovery sostituisce la parte di rete dell'indirizzo IP originale (10.1.1) e mantiene l'indirizzo host (.50) dell'indirizzo IP originale (10.1.1.50).  Per VM1, NetApp Disaster Recovery esamina le impostazioni CIDR per NetworkB e utilizza la porzione di rete NetworkB 192.168.1, mantenendo la porzione host (.50) per creare il nuovo indirizzo IP per VM1.  Il nuovo IP diventa 192.168.1.50.

In sintesi, l'indirizzo host rimane lo stesso, mentre l'indirizzo di rete viene sostituito con quello configurato nella mappatura della subnet del sito.  Ciò consente di gestire più facilmente la riassegnazione degli indirizzi IP in caso di failover, soprattutto se si hanno centinaia di reti e migliaia di VM da gestire.

Per i dettagli sull'inclusione della mappatura delle subnet nei tuoi siti, fai riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Aggiungi siti server vCenter"] .



=== Protezione contro gli ostacoli

Ora è possibile ignorare la protezione in modo che il servizio non crei automaticamente una relazione di protezione inversa dopo un failover del piano di replica.  Questa opzione è utile se si desidera eseguire operazioni aggiuntive sul sito ripristinato prima di riportarlo online in NetApp Disaster Recovery.

Quando si avvia un failover, per impostazione predefinita il servizio crea automaticamente una relazione di protezione inversa per ogni volume nel piano di replica, se il sito di origine originale è online.  Ciò significa che il servizio crea una relazione SnapMirror dal sito di destinazione al sito di origine.  Il servizio inverte automaticamente anche la relazione SnapMirror quando si avvia un failback.

Quando si avvia un failover, ora è possibile scegliere l'opzione *Salta protezione*.  In questo modo il servizio non inverte automaticamente la relazione SnapMirror .  Invece, lascia il volume scrivibile su entrambi i lati del piano di replicazione.

Dopo che il sito di origine originale è di nuovo online, è possibile stabilire la protezione inversa selezionando *Proteggi risorse* dal menu Azioni del piano di replica.  In questo modo si tenta di creare una relazione di replicazione inversa per ogni volume nel piano.  È possibile eseguire questo processo più volte finché la protezione non viene ripristinata.  Una volta ripristinata la protezione, è possibile avviare un failback nel modo consueto.

Per i dettagli sulla protezione da salto, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Eseguire il failover delle applicazioni su un sito remoto"] .



=== Aggiornamenti della pianificazione SnapMirror nel piano di replica

NetApp Disaster Recovery supporta ora l'uso di soluzioni di gestione degli snapshot esterni, come lo scheduler di policy nativo ONTAP SnapMirror o integrazioni di terze parti con ONTAP.  Se ogni datastore (volume) nel piano di replicazione ha già una relazione SnapMirror gestita altrove, è possibile utilizzare tali snapshot come punti di ripristino in NetApp Disaster Recovery.

Per configurare, nella sezione Piano di replica > Mapping delle risorse, selezionare la casella di controllo *Usa backup e pianificazioni di conservazione gestiti dalla piattaforma* durante la configurazione del mapping dei datastore.

Quando l'opzione è selezionata, NetApp Disaster Recovery non configura una pianificazione di backup.  Tuttavia, è comunque necessario configurare una pianificazione di conservazione perché potrebbero essere comunque acquisiti snapshot per operazioni di test, failover e failback.

Dopo aver configurato questa funzionalità, il servizio non esegue snapshot programmati regolarmente, ma si affida all'entità esterna per l'esecuzione e l'aggiornamento di tali snapshot.

Per i dettagli sull'utilizzo di soluzioni snapshot esterne nel piano di replica, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



== 16 aprile 2025

Versione 4.2.2



=== Rilevamento pianificato per le VM

NetApp Disaster Recovery esegue la rilevazione una volta ogni 24 ore.  Con questa versione, ora puoi personalizzare la pianificazione dell'individuazione in base alle tue esigenze e ridurre l'impatto sulle prestazioni quando necessario.  Ad esempio, se si dispone di un numero elevato di VM, è possibile impostare la pianificazione dell'individuazione in modo che venga eseguita ogni 48 ore.  Se si dispone di un numero limitato di VM, è possibile impostare la pianificazione dell'individuazione in modo che venga eseguita ogni 12 ore.

Se non si desidera pianificare l'individuazione, è possibile disattivare l'opzione di individuazione pianificata e aggiornare manualmente l'individuazione in qualsiasi momento.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Aggiungi siti server vCenter"] .



=== Supporto del datastore del gruppo di risorse

In precedenza, era possibile creare gruppi di risorse solo tramite VM.  Con questa versione è possibile creare un gruppo di risorse in base ai datastore.  Quando si crea un piano di replicazione e si crea un gruppo di risorse per tale piano, verranno elencate tutte le VM in un datastore.  Questa opzione è utile se si dispone di un numero elevato di VM e si desidera raggrupparle in base al datastore.

È possibile creare un gruppo di risorse con un datastore nei seguenti modi:

* Quando si aggiunge un gruppo di risorse tramite datastore, è possibile visualizzare un elenco di datastore.  È possibile selezionare uno o più datastore per creare un gruppo di risorse.
* Quando si crea un piano di replicazione e si crea un gruppo di risorse all'interno del piano, è possibile visualizzare le VM nei datastore.


Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Notifiche di prova gratuita o scadenza della licenza

Questa versione fornisce notifiche che la prova gratuita scadrà tra 60 giorni per garantire che tu abbia il tempo di ottenere una licenza.  Questa versione fornisce anche notifiche il giorno in cui scade la licenza.



=== Notifica degli aggiornamenti del servizio

Con questa versione, nella parte superiore viene visualizzato un banner per indicare che i servizi vengono aggiornati e che il servizio è in modalità di manutenzione.  Il banner appare quando il servizio è in fase di aggiornamento e scompare al termine dell'aggiornamento.  Mentre l'aggiornamento è in corso, puoi continuare a lavorare nell'interfaccia utente, ma non puoi inviare nuovi lavori.  I lavori pianificati verranno eseguiti una volta completato l'aggiornamento e il servizio tornerà in modalità di produzione.



== 10 marzo 2025

Versione 4.2.1



=== Supporto proxy intelligente

L'agente NetApp Console supporta il proxy intelligente.  Il proxy intelligente è un modo leggero, sicuro ed efficiente per connettere il tuo sistema locale a NetApp Disaster Recovery.  Fornisce una connessione sicura tra il tuo sistema e NetApp Disaster Recovery senza richiedere una VPN o un accesso diretto a Internet.  Questa implementazione proxy ottimizzata scarica il traffico API all'interno della rete locale.

Quando viene configurato un proxy, NetApp Disaster Recovery tenta di comunicare direttamente con VMware o ONTAP e utilizza il proxy configurato se la comunicazione diretta fallisce.

L'implementazione del proxy NetApp Disaster Recovery richiede la comunicazione sulla porta 443 tra l'agente della console e tutti i server vCenter e gli array ONTAP che utilizzano un protocollo HTTPS.  L'agente NetApp Disaster Recovery all'interno dell'agente Console comunica direttamente con VMware vSphere, VC o ONTAP quando esegue qualsiasi azione.

Per ulteriori informazioni sul proxy intelligente per NetApp Disaster Recovery, vedere https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Configura la tua infrastruttura per NetApp Disaster Recovery"] .

Per ulteriori informazioni sulla configurazione generale del proxy nella NetApp Console, vedere https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configurare l'agente della console per utilizzare un server proxy"^] .



=== Interrompi la prova gratuita in qualsiasi momento

Puoi interrompere la prova gratuita in qualsiasi momento oppure attendere la sua scadenza.

Vedere https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Termina la prova gratuita"] .



== 19 febbraio 2025

Versione 4.2



=== Supporto ASA r2 per VM e datastore su storage VMFS

Questa versione di NetApp Disaster Recovery fornisce supporto per ASA r2 per VM e datastore su storage VMFS.  Su un sistema ASA r2, il software ONTAP supporta le funzionalità SAN essenziali, rimuovendo al contempo le funzionalità non supportate negli ambienti SAN.

Questa versione supporta le seguenti funzionalità per ASA r2:

* Provisioning del gruppo di coerenza per l'archiviazione primaria (solo gruppo di coerenza flat, ovvero un solo livello senza una struttura gerarchica)
* Operazioni di backup (gruppo di coerenza) inclusa l'automazione SnapMirror


Il supporto per ASA r2 in NetApp Disaster Recovery utilizza ONTAP 9.16.1.

Sebbene i datastore possano essere montati su un volume ONTAP o su un'unità di storage ASA r2, un gruppo di risorse in NetApp Disaster Recovery non può includere sia un datastore da ONTAP che uno da ASA r2.  È possibile selezionare un datastore da ONTAP o un datastore da ASA r2 in un gruppo di risorse.



== 30 ottobre 2024



=== Segnalazione

Ora puoi generare e scaricare report che ti aiuteranno ad analizzare il tuo panorama.  I report predefiniti riepilogano i failover e i failback, mostrano i dettagli della replica su tutti i siti e mostrano i dettagli dei processi degli ultimi sette giorni.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Creare report di ripristino di emergenza"] .



=== Prova gratuita di 30 giorni

Ora puoi registrarti per una prova gratuita di 30 giorni di NetApp Disaster Recovery.  In precedenza, le prove gratuite duravano 90 giorni.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Impostare la licenza"] .



=== Disabilitare e abilitare i piani di replicazione

Una versione precedente includeva aggiornamenti alla struttura della pianificazione dei test di failover, necessari per supportare le pianificazioni giornaliere e settimanali.  Questo aggiornamento richiedeva di disabilitare e riabilitare tutti i piani di replica esistenti, in modo da poter utilizzare le nuove pianificazioni dei test di failover giornalieri e settimanali.  Si tratta di un requisito una tantum.

Ecco come fare:

. Dal menu, seleziona *Piani di replicazione*.
. Selezionare un piano e fare clic sull'icona Azioni per visualizzare il menu a discesa.
. Selezionare *Disabilita*.
. Dopo qualche minuto, seleziona *Abilita*.




=== Mappatura delle cartelle

Quando si crea un piano di replica e si mappano le risorse di elaborazione, è ora possibile mappare le cartelle in modo che le VM vengano ripristinate in una cartella specificata per data center, cluster e host.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Dettagli della VM disponibili per failover, failback e failover di prova

Quando si verifica un errore e si avvia un failover, si esegue un failback o si testa il failover, ora è possibile visualizzare i dettagli delle VM e identificare quali VM non sono state riavviate.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Eseguire il failover delle applicazioni su un sito remoto"] .



=== Ritardo di avvio della VM con sequenza di avvio ordinata

Quando si crea un piano di replica, è ora possibile impostare un ritardo di avvio per ogni macchina virtuale nel piano.  Ciò consente di impostare una sequenza di avvio delle VM per garantire che tutte le VM con priorità uno siano in esecuzione prima dell'avvio delle VM con priorità successiva.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Informazioni sul sistema operativo della VM

Quando si crea un piano di replicazione, è ora possibile visualizzare il sistema operativo per ogni macchina virtuale nel piano.  Ciò è utile per decidere come raggruppare le VM in un gruppo di risorse.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Aliasing del nome della VM

Quando si crea un piano di replica, è ora possibile aggiungere un prefisso e un suffisso ai nomi delle VM sul sito di disaster recovery.  Ciò consente di utilizzare un nome più descrittivo per le VM nel piano.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Pulisci i vecchi snapshot

È possibile eliminare tutti gli snapshot che non sono più necessari oltre il numero di conservazione specificato.  Gli snapshot potrebbero accumularsi nel tempo quando si riduce il numero di snapshot conservati; ora è possibile rimuoverli per liberare spazio.  Puoi farlo in qualsiasi momento su richiesta o quando elimini un piano di replicazione.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestisci siti, gruppi di risorse, piani di replica, datastore e informazioni sulle macchine virtuali"] .



=== Riconciliare gli snapshot

Ora puoi riconciliare gli snapshot non sincronizzati tra l'origine e la destinazione.  Ciò potrebbe verificarsi se gli snapshot vengono eliminati su una destinazione esterna a NetApp Disaster Recovery.  Il servizio elimina automaticamente lo snapshot sulla sorgente ogni 24 ore.  Tuttavia, è possibile eseguire questa operazione su richiesta.  Questa funzionalità consente di garantire che gli snapshot siano coerenti in tutti i siti.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestire i piani di replicazione"] .



== 20 settembre 2024



=== Supporto per datastore VMware VMFS da locale a locale

Questa versione include il supporto per le VM montate su datastore VMware vSphere Virtual Machine File System (VMFS) per iSCSI e FC protetti su storage locale.  In precedenza, il servizio forniva un'anteprima tecnologica che supportava gli archivi dati VMFS per iSCSI e FC.

Ecco alcune considerazioni aggiuntive riguardanti i protocolli iSCSI e FC:

* Il supporto FC è per i protocolli front-end client, non per la replica.
* NetApp Disaster Recovery supporta solo una singola LUN per volume ONTAP .  Il volume non deve avere più LUN.
* Per qualsiasi piano di replica, il volume ONTAP di destinazione deve utilizzare gli stessi protocolli del volume ONTAP di origine che ospita le VM protette.  Ad esempio, se la sorgente utilizza un protocollo FC, anche la destinazione dovrebbe utilizzare FC.




== 02 agosto 2024



=== Supporto per datastore VMware VMFS da locale a locale per FC

Questa versione include un'anteprima tecnologica del supporto per le VM montate su datastore VMware vSphere Virtual Machine File System (VMFS) per FC protette su storage locale.  In precedenza, il servizio forniva un'anteprima tecnologica che supportava i datastore VMFS per iSCSI.


NOTE: NetApp non addebita alcun costo per la capacità di carico di lavoro visualizzata in anteprima.



=== Annullamento del lavoro

Con questa versione, è ora possibile annullare un lavoro nell'interfaccia utente di Job Monitor.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Monitorare i lavori"] .



== 17 luglio 2024



=== Pianificazioni dei test di failover

Questa versione include aggiornamenti alla struttura della pianificazione dei test di failover, necessari per supportare le pianificazioni giornaliere e settimanali.  Questo aggiornamento richiede di disabilitare e riabilitare tutti i piani di replica esistenti, in modo da poter utilizzare le nuove pianificazioni dei test di failover giornalieri e settimanali.  Si tratta di un requisito una tantum.

Ecco come fare:

. Dal menu, seleziona *Piani di replicazione*.
. Selezionare un piano e fare clic sull'icona Azioni per visualizzare il menu a discesa.
. Selezionare *Disabilita*.
. Dopo qualche minuto, seleziona *Abilita*.




=== Aggiornamenti del piano di replicazione

Questa versione include aggiornamenti ai dati del piano di replica, che risolvono il problema "snapshot non trovato".  Per fare ciò, è necessario modificare il conteggio di conservazione in tutti i piani di replica su 1 e avviare uno snapshot su richiesta.  Questo processo crea un nuovo backup e rimuove tutti i backup precedenti.

Ecco come fare:

. Dal menu, seleziona *Piani di replicazione*.
. Selezionare il piano di replicazione, selezionare la scheda *Failover mapping* e selezionare l'icona della matita *Modifica*.
. Selezionare la freccia *Datastore* per espanderla.
. Prendere nota del valore del conteggio di conservazione nel piano di replica. Una volta completati questi passaggi, è necessario ripristinare il valore originale.
. Ridurre il conteggio a 1.
. Avvia uno snapshot su richiesta. Per farlo, nella pagina Piano di replica, seleziona il piano, seleziona l'icona Azioni e seleziona *Esegui snapshot ora*.
. Dopo aver completato correttamente il processo di snapshot, riportare il conteggio nel piano di replica al valore originale annotato nel primo passaggio.
. Ripetere questi passaggi per tutti i piani di replicazione esistenti.




== 05 luglio 2024

Questa versione NetApp Disaster Recovery include i seguenti aggiornamenti:



=== Supporto per la serie AFF A

Questa versione supporta le piattaforme hardware NetApp AFF serie A.



=== Supporto per datastore VMware VMFS da locale a locale

Questa versione include un'anteprima tecnologica del supporto per le VM montate su datastore VMware vSphere Virtual Machine File System (VMFS) protetti su storage locale.  Con questa versione, il disaster recovery è supportato in un'anteprima tecnologica per carichi di lavoro VMware on-premise in ambienti VMware on-premise con datastore VMFS.


NOTE: NetApp non addebita alcun costo per la capacità di carico di lavoro visualizzata in anteprima.



=== Aggiornamenti del piano di replicazione

È possibile aggiungere un piano di replicazione più facilmente filtrando le VM in base all'archivio dati nella pagina Applicazioni e selezionando maggiori dettagli sulla destinazione nella pagina Mappatura risorse. Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Modifica i piani di replicazione

Con questa versione, la pagina dei mapping di failover è stata migliorata per renderla più chiara.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestire i piani"] .



=== Modifica VM

Con questa versione, il processo di modifica delle VM nel piano ha incluso alcuni piccoli miglioramenti all'interfaccia utente.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestire le VM"] .



=== Aggiornamenti failover

Prima di avviare un failover, è ora possibile determinare lo stato delle VM e se sono accese o spente.  Il processo di failover ora consente di acquisire uno snapshot subito o di scegliere gli snapshot.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Eseguire il failover delle applicazioni su un sito remoto"] .



=== Pianificazioni dei test di failover

Ora è possibile modificare i test di failover e impostare pianificazioni giornaliere, settimanali e mensili per i test di failover.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestire i piani"] .



=== Aggiornamenti alle informazioni prerequisite

Le informazioni sui prerequisiti NetApp Disaster Recovery sono state aggiornate.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Prerequisiti NetApp Disaster Recovery"] .



== 15 maggio 2024

Questa versione NetApp Disaster Recovery include i seguenti aggiornamenti:



=== Replica dei carichi di lavoro VMware da locale a locale

Questa funzionalità è ora disponibile a tutti.  In precedenza si trattava di un'anteprima tecnologica con funzionalità limitate.



=== Aggiornamenti sulle licenze

Con NetApp Disaster Recovery puoi registrarti per una prova gratuita di 90 giorni, acquistare un abbonamento pay-as-you-go (PAYGO) con Amazon Marketplace o Bring Your Own License (BYOL), ovvero un file di licenza NetApp (NLF) che puoi ottenere dal tuo rappresentante commerciale NetApp o dal sito di supporto NetApp (NSS).

Per i dettagli sulla configurazione delle licenze per NetApp Disaster Recovery, fare riferimento alink:../get-started/dr-licensing.html["Impostare la licenza"] .

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Scopri di più su NetApp Disaster Recovery"] .



== 05 marzo 2024

Questa è la versione di disponibilità generale di NetApp Disaster Recovery, che include i seguenti aggiornamenti.



=== Aggiornamenti sulle licenze

Con NetApp Disaster Recovery puoi registrarti per una prova gratuita di 90 giorni oppure puoi optare per la soluzione BYOL (Bring Your Own License), ovvero un file di licenza NetApp (NLF) che puoi ottenere dal tuo rappresentante commerciale NetApp .  È possibile utilizzare il numero di serie della licenza per attivare BYOL negli abbonamenti NetApp Console .  I costi di NetApp Disaster Recovery si basano sulla capacità fornita dei datastore.

Per i dettagli sulla configurazione delle licenze per NetApp Disaster Recovery, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Impostare la licenza"] .

Per i dettagli sulla gestione delle licenze per *tutti* i servizi dati NetApp Console , fare riferimento a https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Gestisci le licenze per tutti i servizi dati NetApp Console"^] .



=== Modificare gli orari

Con questa versione, è ora possibile impostare pianificazioni per testare la conformità e i test di failover, in modo da garantire che funzionino correttamente quando necessario.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare il piano di replicazione"] .



== 01 febbraio 2024

Questa versione di anteprima NetApp Disaster Recovery include i seguenti aggiornamenti:



=== Miglioramento della rete

Con questa versione è ora possibile ridimensionare i valori della CPU e della RAM della VM.  Ora è anche possibile selezionare un indirizzo IP statico o DHCP di rete per la VM.

* DHCP: se si sceglie questa opzione, è necessario fornire le credenziali per la VM.
* IP statico: è possibile selezionare le stesse informazioni o informazioni diverse dalla VM di origine.  Se si sceglie lo stesso della fonte, non è necessario immettere le credenziali.  D'altro canto, se si sceglie di utilizzare informazioni diverse dalla fonte, è possibile fornire le credenziali, l'indirizzo IP, la maschera di sottorete, il DNS e le informazioni sul gateway.


Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Script personalizzati

Ora possono essere inclusi come processi post-failover.  Con gli script personalizzati, puoi far sì che NetApp Disaster Recovery esegua lo script dopo un processo di failover.  Ad esempio, è possibile utilizzare uno script personalizzato per riprendere tutte le transazioni del database una volta completato il failover.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover su un sito remoto"] .



=== Relazione SnapMirror

Ora è possibile creare una relazione SnapMirror durante lo sviluppo del piano di replica.  In precedenza, era necessario creare la relazione all'esterno di NetApp Disaster Recovery.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Gruppi di coerenza

Quando si crea un piano di replica, è possibile includere VM provenienti da volumi diversi e SVM diversi.  NetApp Disaster Recovery crea uno snapshot del gruppo di coerenza includendo tutti i volumi e aggiorna tutte le posizioni secondarie.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Opzione di ritardo di accensione della VM

Quando si crea un piano di replicazione, è possibile aggiungere VM a un gruppo di risorse.  Con i gruppi di risorse è possibile impostare un ritardo su ogni macchina virtuale in modo che si accendano in una sequenza ritardata.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Copie snapshot coerenti con l'applicazione

È possibile specificare di creare copie Snapshot coerenti con l'applicazione.  Il servizio metterà in pausa l'applicazione e poi eseguirà uno snapshot per ottenere uno stato coerente dell'applicazione.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



== 11 gennaio 2024

Questa versione di anteprima di NetApp Disaster Recovery include i seguenti aggiornamenti:



=== Dashboard più veloce

Con questa versione, è possibile accedere più rapidamente alle informazioni su altre pagine della Dashboard.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Scopri di più su NetApp Disaster Recovery"] .



== 20 ottobre 2023

Questa versione di anteprima di NetApp Disaster Recovery include i seguenti aggiornamenti.



=== Proteggere i carichi di lavoro VMware basati su NFS in sede

Ora con NetApp Disaster Recovery puoi proteggere i tuoi carichi di lavoro VMware on-premise basati su NFS da disastri su un altro ambiente VMware on-premise basato su NFS, oltre che sul cloud pubblico.  NetApp Disaster Recovery orchestra il completamento dei piani di disaster recovery.


NOTE: Con questa offerta di anteprima, NetApp si riserva il diritto di modificare i dettagli, i contenuti e la tempistica dell'offerta prima della disponibilità generale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Scopri di più su NetApp Disaster Recovery"] .



== 27 settembre 2023

Questa versione di anteprima di NetApp Disaster Recovery include i seguenti aggiornamenti:



=== Aggiornamenti della dashboard

Ora puoi selezionare le opzioni nella Dashboard, rendendo più semplice e veloce la consultazione delle informazioni. Inoltre, la Dashboard ora mostra lo stato dei failover e delle migrazioni.

Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Visualizza lo stato di salute dei tuoi piani di disaster recovery nella Dashboard"] .



=== Aggiornamenti del piano di replicazione

* *RPO*: ora è possibile immettere l'RPO (Recovery Point Objective) e il conteggio della conservazione nella sezione Datastore del piano di replica. Indica la quantità di dati che devono esistere e che non siano più vecchi del tempo impostato. Ad esempio, se lo si imposta su 5 minuti, in caso di disastro il sistema può perdere fino a 5 minuti di dati senza compromettere le esigenze aziendali critiche.
+
Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .

* *Miglioramenti della rete*: quando si esegue il mapping della rete tra le posizioni di origine e di destinazione nella sezione delle macchine virtuali del piano di replica, NetApp Disaster Recovery offre ora due opzioni: DHCP o IP statico. In precedenza era supportato solo DHCP. Per gli IP statici, è necessario configurare la subnet, il gateway e i server DNS. Inoltre, ora è possibile immettere le credenziali per le macchine virtuali.
+
Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .

* *Modifica pianificazioni*: ora puoi aggiornare le pianificazioni del piano di replicazione.
+
Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestire le risorse"] .

* * Automazione SnapMirror *: durante la creazione del piano di replica in questa versione, è possibile definire la relazione SnapMirror tra volumi di origine e di destinazione in una delle seguenti configurazioni:
+
** 1 a 1
** 1 a molti in un'architettura fanout
** Molti a 1 come gruppo di coerenza
** Molti a molti
+
Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .







== 01 agosto 2023



=== Anteprima di NetApp Disaster Recovery

NetApp Disaster Recovery Preview è un servizio di disaster recovery basato su cloud che automatizza i flussi di lavoro di disaster recovery.  Inizialmente, con l'anteprima di NetApp Disaster Recovery , puoi proteggere i tuoi carichi di lavoro VMware on-premise basati su NFS che eseguono lo storage NetApp su VMware Cloud (VMC) su AWS con Amazon FSx for ONTAP.


NOTE: Con questa offerta di anteprima, NetApp si riserva il diritto di modificare i dettagli, i contenuti e la tempistica dell'offerta prima della disponibilità generale.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Scopri di più su NetApp Disaster Recovery"] .

Questa versione include i seguenti aggiornamenti:



=== Aggiornamento dei gruppi di risorse per l'ordine di avvio

Quando si crea un piano di disaster recovery o di replicazione, è possibile aggiungere macchine virtuali a gruppi di risorse funzionali. I gruppi di risorse consentono di inserire un set di macchine virtuali dipendenti in gruppi logici che soddisfano i requisiti. Ad esempio, i gruppi potrebbero contenere un ordine di avvio che può essere eseguito al momento del ripristino. Con questa versione, ogni gruppo di risorse può includere una o più macchine virtuali. Le macchine virtuali si accenderanno in base alla sequenza in cui le hai incluse nel piano. Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Selezionare le applicazioni da replicare e assegnare gruppi di risorse"] .



=== Verifica della replicazione

Dopo aver creato il piano di disaster recovery o di replica, identificato la ricorrenza nella procedura guidata e avviato una replica su un sito di disaster recovery, ogni 30 minuti NetApp Disaster Recovery verifica che la replica stia effettivamente avvenendo secondo il piano. È possibile monitorare l'avanzamento nella pagina Job Monitor. Fare riferimento a  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Replicare le applicazioni su un altro sito"] .



=== Il piano di replicazione mostra le pianificazioni di trasferimento dell'obiettivo del punto di ripristino (RPO)

Quando si crea un piano di disaster recovery o di replicazione, si selezionano le VM. In questa versione è ora possibile visualizzare lo SnapMirror associato a ciascuno dei volumi associati al datastore o alla VM. È anche possibile visualizzare le pianificazioni dei trasferimenti RPO associate alla pianificazione SnapMirror . RPO ti aiuta a determinare se la tua pianificazione di backup è sufficiente per il ripristino dopo un disastro. Fare riferimento a https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"] .



=== Aggiornamento del Job Monitor

La pagina Job Monitor ora include un'opzione Aggiorna, che consente di ottenere uno stato aggiornato delle operazioni. Fare riferimento a  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Monitorare i lavori di ripristino di emergenza"] .



== 18 maggio 2023

Questa è la versione iniziale di NetApp Disaster Recovery.



=== Servizio di disaster recovery basato su cloud

NetApp Disaster Recovery è un servizio di disaster recovery basato su cloud che automatizza i flussi di lavoro di disaster recovery.  Inizialmente, con l'anteprima di NetApp Disaster Recovery , puoi proteggere i tuoi carichi di lavoro VMware on-premise basati su NFS che eseguono lo storage NetApp su VMware Cloud (VMC) su AWS con Amazon FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Scopri di più su NetApp Disaster Recovery"] .
